refactored lightly - this causes an error same as earlier one ()
Step failed
java.lang.IllegalArgumentException: adding container's parent to itself
	at java.desktop/java.awt.Container.checkAddToSelf(Container.java:505)
	at java.desktop/java.awt.Container.addImpl(Container.java:1118)
	at java.desktop/java.awt.Container.add(Container.java:440)
	at Main.Module.ModuleUI.add(ModuleUI.java:80)
	at Main.Module.MPSModule.addModule(MPSModule.java:65)
	at Main.Module.MPSModule.move(MPSModule.java:40)
	at test.java.StepDefMovingModules.aRandomModuleIsMovedAroundRandomlyTimesWhistBeingTracked(StepDefMovingModules.java:34)
	at ✽.A random module is moved around randomly 1000 times whist being tracked(file:///Users/jennyjames-ross/IdeaProjects/Modular-Productivity-Software/src/test/Resources/MovingModules.feature:5)